In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OrdinalEncoder

In [2]:
from sklearn.metrics import classification_report, confusion_matrix, r2_score, mean_squared_error, mean_absolute_error

In [3]:
import warnings
warnings.filterwarnings("ignore")

Датасет про питьевые воды

In [4]:
df_cat = pd.read_csv("../data/water_potability_preprocessed.csv")
df_cat = df_cat.iloc[:, 1:]
df_cat

ph    Hardness        Solids  Chloramines     Sulfate  \
0     7.080795  204.890455  20791.318981     7.300212  368.516441   
1     3.716080  129.422921  18630.057858     6.635246  333.775777   
2     8.099124  224.236259  19909.541732     9.275884  333.775777   
3     8.316766  214.373394  22018.417441     8.059332  356.886136   
4     9.092223  181.101509  17978.986339     6.546600  310.135738   
...        ...         ...           ...          ...         ...   
3271  4.668102  193.681735  47580.991603     7.166639  359.948574   
3272  7.808856  193.553212  17329.802160     8.061362  333.775777   
3273  9.419510  175.762646  33155.578218     7.350233  333.775777   
3274  5.126763  230.603758  11983.869376     6.303357  333.775777   
3275  7.874671  195.102299  17404.177061     7.509306  333.775777   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       564.308654       10.379783        86.990970   2.963135           0  
1       592.885359       15.180013        56.329076   4.500656           0  
2       418.606213       16.868637        66.420093   3.055934           0  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
...            ...             ...              ...        ...         ...  
3271    526.424171       13.894419        66.687695   4.435821           1  
3272    392.449580       19.903225        66.396293   2.798243           1  
3273    432.044783       11.039070        69.845400   3.298875           1  
3274    402.883113       11.168946        77.488213   4.708658           1  
3275    327.459760       16.140368        78.698446   2.309149           1  

[3276 rows x 10 columns]

In [5]:
X_cat = df_cat.iloc[:, :-1].values # все признаки, кроме целевого
y_cat = df_cat['Potability'].values # целевой признак

In [6]:
X_cat_train, X_cat_test, y_cat_train, y_cat_test = train_test_split(X_cat, y_cat, test_size=0.20, random_state=42)

In [7]:
scaler = StandardScaler()

X_cat_train = scaler.fit_transform(X_cat_train)
X_cat_test = scaler.transform(X_cat_test)

Датасет автомобили

In [8]:
df_reg = pd.read_csv('../data/automobile_preprocessed.csv')
df_reg = df_reg.iloc[:, 1:]
df_reg['make'] = OrdinalEncoder().fit_transform(df_reg[["make"]])
df_reg

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0            3                122   0.0          0           0             1   
1            3                122   0.0          0           0             1   
2            1                122   0.0          0           0             1   
3            2                164   1.0          0           0             0   
4            2                164   1.0          0           0             0   
..         ...                ...   ...        ...         ...           ...   
188         -1                 95  20.0          0           0             0   
189         -1                 95  20.0          0           1             0   
190         -1                 95  20.0          0           0             0   
191         -1                 95  20.0          1           1             0   
192         -1                 95  20.0          0           1             0   

     drive-wheels  engine-location  wheel-base  length  ...  \
0               2                0        88.6   168.8  ...   
1               2                0        88.6   168.8  ...   
2               2                0        94.5   171.2  ...   
3               1                0        99.8   176.6  ...   
4               0                0        99.4   176.6  ...   
..            ...              ...         ...     ...  ...   
188             2                0       109.1   188.8  ...   
189             2                0       109.1   188.8  ...   
190             2                0       109.1   188.8  ...   
191             2                0       109.1   188.8  ...   
192             2                0       109.1   188.8  ...   

     num-of-cylinders_six  num-of-cylinders_three  num-of-cylinders_twelve  \
0                       0                       0                        0   
1                       0                       0                        0   
2                       1                       0                        0   
3                       0                       0                        0   
4                       0                       0                        0   
..                    ...                     ...                      ...   
188                     0                       0                        0   
189                     0                       0                        0   
190                     1                       0                        0   
191                     1                       0                        0   
192                     0                       0                        0   

     fuel-system_1bbl  fuel-system_2bbl  fuel-system_idi  fuel-system_mfi  \
0                   0                 0                0                0   
1                   0                 0                0                0   
2                   0                 0                0                0   
3                   0                 0                0                0   
4                   0                 0                0                0   
..                ...               ...              ...              ...   
188                 0                 0                0                0   
189                 0                 0                0                0   
190                 0                 0                0                0   
191                 0                 0                1                0   
192                 0                 0                0                0   

     fuel-system_mpfi  fuel-system_spdi  fuel-system_spfi  
0                   1                 0                 0  
1                   1                 0                 0  
2                   1                 0                 0  
3                   1                 0                 0  
4                   1                 0                 0  
..                ...               ...               ...  
188  

In [9]:
X_reg = df_reg.drop(columns=['price']).values # все признаки, кроме целевого
y_reg = df_reg['price'].values # целевой признак

In [10]:
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(X_reg, y_reg, test_size=0.20, random_state=42)

In [11]:
scaler = StandardScaler()

X_reg_train = scaler.fit_transform(X_reg_train)
X_reg_test = scaler.transform(X_reg_test)

# Task 1

In [12]:
from sklearn import ensemble, svm, linear_model
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB

Бэггинг

In [13]:
clf = ensemble.BaggingClassifier()
clf.fit(X_cat_train, y_cat_train)

BaggingClassifier()

In [14]:
y_pred = clf.predict(X_cat_test)
print(confusion_matrix(y_cat_test, y_pred))
print(classification_report(y_cat_test, y_pred))
print(clf.score(X_cat_test, y_cat_test))

[[345  67]
 [160  84]]
              precision    recall  f1-score   support

           0       0.68      0.84      0.75       412
           1       0.56      0.34      0.43       244

    accuracy                           0.65       656
   macro avg       0.62      0.59      0.59       656
weighted avg       0.64      0.65      0.63       656

0.6539634146341463


In [15]:
clf = ensemble.BaggingRegressor()
clf.fit(X_reg_train, y_reg_train)

BaggingRegressor()

In [16]:
y_pred = clf.predict(X_reg_test)
print("R2:", r2_score(y_reg_test, y_pred))
print("MSE:", mean_squared_error(y_reg_test, y_pred))
print("RMSE:", mean_squared_error(y_reg_test, y_pred, squared=False))
print("MAE:", mean_absolute_error(y_reg_test, y_pred))

R2: 0.9506217348818251
MSE: 5548878.132763533
RMSE: 2355.6056827838424
MAE: 1376.6905982905982


Бустинг

In [17]:
clf = ensemble.GradientBoostingClassifier()
clf.fit(X_cat_train, y_cat_train)

GradientBoostingClassifier()

In [18]:
y_pred = clf.predict(X_cat_test)
print(confusion_matrix(y_cat_test, y_pred))
print(classification_report(y_cat_test, y_pred))
print(clf.score(X_cat_test, y_cat_test))

[[370  42]
 [182  62]]
              precision    recall  f1-score   support

           0       0.67      0.90      0.77       412
           1       0.60      0.25      0.36       244

    accuracy                           0.66       656
   macro avg       0.63      0.58      0.56       656
weighted avg       0.64      0.66      0.61       656

0.6585365853658537


In [19]:
clf = ensemble.GradientBoostingRegressor()
clf.fit(X_reg_train, y_reg_train)

GradientBoostingRegressor()

In [20]:
y_pred = clf.predict(X_reg_test)
print("R2:", r2_score(y_reg_test, y_pred))
print("MSE:", mean_squared_error(y_reg_test, y_pred))
print("RMSE:", mean_squared_error(y_reg_test, y_pred, squared=False))
print("MAE:", mean_absolute_error(y_reg_test, y_pred))

R2: 0.9414179041133914
MSE: 6583157.793387322
RMSE: 2565.766511860992
MAE: 1464.5528725096135


Стекинг

In [21]:
estimators = [
    ('kNN', GridSearchCV(KNeighborsClassifier(), {'n_neighbors': np.arange(1,6,1)})),
    ('DTC', GridSearchCV(DecisionTreeClassifier(random_state=42), {'max_depth': np.arange(1,15,1), 
                                                                   'max_features': np.arange(5,X_cat.shape[1]-1,1)})),
    ('NB', GaussianNB()),
    ('SVM', GridSearchCV(svm.SVC(random_state=42), {'C': np.arange(0.1,1.1,0.1), 'degree': np.arange(2,5,1)})),
    ('LogReg', GridSearchCV(linear_model.LogisticRegression(random_state=42), {'C': np.arange(0.1,1.1,0.1)}))
]

In [22]:
%%time
clf = ensemble.StackingClassifier(estimators)
clf.fit(X_cat_train, y_cat_train)

Wall time: 2min 50s


StackingClassifier(estimators=[('kNN',
                                GridSearchCV(estimator=KNeighborsClassifier(),
                                             param_grid={'n_neighbors': array([1, 2, 3, 4, 5])})),
                               ('DTC',
                                GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                                             param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                                                         'max_features': array([5, 6, 7])})),
                               ('NB', GaussianNB()),
                               ('SVM',
                                GridSearchCV(estimator=SVC(random_state=42),
                                             param_grid={'C': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
                                                         'degree': array([2, 3, 4])})),
                               ('LogReg',

In [23]:
y_pred = clf.predict(X_cat_test)
print(confusion_matrix(y_cat_test, y_pred))
print(classification_report(y_cat_test, y_pred))
print(clf.score(X_cat_test, y_cat_test))

[[367  45]
 [153  91]]
              precision    recall  f1-score   support

           0       0.71      0.89      0.79       412
           1       0.67      0.37      0.48       244

    accuracy                           0.70       656
   macro avg       0.69      0.63      0.63       656
weighted avg       0.69      0.70      0.67       656

0.698170731707317


In [24]:
estimators = [
    ('LinReg', linear_model.LinearRegression()),
    ('DTR', GridSearchCV(DecisionTreeRegressor(random_state=42), {'max_depth': np.arange(1,15,1), 
                                                                  'max_features': np.arange(5,X_reg.shape[1]-1,1)})),
    ('Lasso', GridSearchCV(linear_model.Lasso(random_state=42), {'alpha': np.arange(0.1,2.05,0.05)})),
    ('Ridge', GridSearchCV(linear_model.Ridge(random_state=42), {'alpha': np.arange(0.1,2.05,0.05)})),
    ('ElasticNet', GridSearchCV(linear_model.ElasticNet(random_state=42), {'alpha': np.arange(0.1,2.05,0.05), 
                                                                           'l1_ratio': np.arange(0.1,1.1,0.1)}))
]

In [25]:
%%time
clf = ensemble.StackingRegressor(estimators)
clf.fit(X_reg_train, y_reg_train)

Wall time: 50.4 s


StackingRegressor(estimators=[('LinReg', LinearRegression()),
                              ('DTR',
                               GridSearchCV(estimator=DecisionTreeRegressor(random_state=42),
                                            param_grid={'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
                                                        'max_features': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42])})),
                              ('Lasso',
                               GridSearch...
       1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ])})),
                              ('ElasticNet',
                               GridSearchCV(estimator=ElasticNet(random_state=42),
                                            param_grid={'alpha': array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 ,
       0.65, 0.7 , 0.75

In [26]:
y_pred = clf.predict(X_reg_test)
print("R2:", r2_score(y_reg_test, y_pred))
print("MSE:", mean_squared_error(y_reg_test, y_pred))
print("RMSE:", mean_squared_error(y_reg_test, y_pred, squared=False))
print("MAE:", mean_absolute_error(y_reg_test, y_pred))

R2: 0.9230692669362758
MSE: 8645084.257479193
RMSE: 2940.2524139058523
MAE: 2014.0972452537073
